# Generated by Django 4.2.1 on 2023-05-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passworld', to='accounts.signup')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uesr', to='accounts.signup')),
            ],
        ),
    ]
